/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duanmaujava.Views;

import com.mycompany.duanmaujava.Services.ChucVuService;
import com.mycompany.duanmaujava.Services.CuaHangService;
import com.mycompany.duanmaujava.Services.NhanVienService;
import com.mycompany.duanmaujava.Services.impl.ChucVuServiceImpl;
import com.mycompany.duanmaujava.Services.impl.CuaHangServiceImpl;
import com.mycompany.duanmaujava.Services.impl.NhanVienServiceImpl;
import com.mycompany.duanmaujava.Utilities.Enums.TrangThaiNhanVien;
import com.mycompany.duanmaujava.Utilities.Validate;
import com.mycompany.duanmaujava.ViewModels.ViewModelsClass.ChucVuViewModel;
import com.mycompany.duanmaujava.ViewModels.ViewModelsClass.CuaHangViewModel;
import com.mycompany.duanmaujava.ViewModels.ViewModelsClass.NhanVienViewModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class QuanLyThongTinNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    private static final ChucVuService CHUC_VU_SERVICE = new ChucVuServiceImpl();
    private static final CuaHangService CUA_HANG_SERVICE = new CuaHangServiceImpl();
    private static final NhanVienService NHAN_VIEN_SERVICE = new NhanVienServiceImpl();
    private List<NhanVienViewModel> listNhanVien = new ArrayList<>();
    private List<CuaHangViewModel> listCuaHang = new ArrayList<>();
    private List<ChucVuViewModel> listChucVu = new ArrayList<>();
    private DefaultTableModel modelViewCuaHang;
    private DefaultTableModel modelViewChucVu;
    private DefaultTableModel modelViewNhanVien;
    private DefaultComboBoxModel boxModelCuaHang;
    private DefaultComboBoxModel boxModelChucVu;
    private DefaultComboBoxModel boxModelGuiBC;
    private String idCuaHang;
    private String idChucVu;
    private String idNhanVien;
    private int checkCuaHang;
    private int checkchucVu;
    private int checkNhanVien;

    public QuanLyThongTinNhanVien() {
        initComponents();
        modelViewChucVu = (DefaultTableModel) tblChucVu.getModel();
        modelViewCuaHang = (DefaultTableModel) tblCuaHang.getModel();
        boxModelCuaHang = (DefaultComboBoxModel) cbbViewNhanVienCH.getModel();
        boxModelChucVu = (DefaultComboBoxModel) cbbViewNhanVienCV.getModel();
        boxModelGuiBC = (DefaultComboBoxModel) cbbViewNhanVienGuiBC.getModel();
        listChucVu = CHUC_VU_SERVICE.getList();
        listCuaHang = CUA_HANG_SERVICE.getList();
        listNhanVien = NHAN_VIEN_SERVICE.getList();
        getCbb();
        getTableCuaHang(listCuaHang);
        getTableChucVu(listChucVu);
        resetFormChucVu();
        resetFormCuaHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dateViewNhanVienNgaySinhNV = new com.toedter.calendar.JDateChooser();
        txtViewNhanVienMaNV = new javax.swing.JTextField();
        txtViewNhanVienTenNV = new javax.swing.JTextField();
        txtViewNhanVienTenDem = new javax.swing.JTextField();
        txtViewNhanVienHoNV = new javax.swing.JTextField();
        rdViewNhanVienNam = new javax.swing.JRadioButton();
        rdViewNhanVienNu = new javax.swing.JRadioButton();
        txtViewNhanVienDiaChi = new javax.swing.JTextField();
        cbbViewNhanVienCH = new javax.swing.JComboBox<>();
        cbbViewNhanVienCV = new javax.swing.JComboBox<>();
        cbbViewNhanVienTT = new javax.swing.JComboBox<>();
        cbbViewNhanVienGuiBC = new javax.swing.JComboBox<>();
        pwViewNhanVienPass = new javax.swing.JPasswordField();
        btnViewNhanVienSave = new javax.swing.JButton();
        btnViewNhanVienUpdate = new javax.swing.JButton();
        btnViewNhanVienDelete = new javax.swing.JButton();
        btnViewNhanVienReset = new javax.swing.JButton();
        jlViewNhanVienError = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtViewCuaHangMaCuaHang = new javax.swing.JTextField();
        txtViewCuaHangTenCuaHang = new javax.swing.JTextField();
        txtViewCuaHangDiaChi = new javax.swing.JTextField();
        txtViewCuaHangThanhPho = new javax.swing.JTextField();
        txtViewCuaHangQuocGia = new javax.swing.JTextField();
        btntxtViewCuaHangSave = new javax.swing.JButton();
        btnViewCuaHangUpdate = new javax.swing.JButton();
        btnViewCuaHangDelete = new javax.swing.JButton();
        btnViewCuaHangReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCuaHang = new javax.swing.JTable();
        jlViewCuaHangError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaChucVu = new javax.swing.JTextField();
        txtTenChucVu = new javax.swing.JTextField();
        btnViewChucVuAdd = new javax.swing.JButton();
        btnViewChucVuReset = new javax.swing.JButton();
        btnViewChucVuUpdate = new javax.swing.JButton();
        btnViewChucVuDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jlViewChucVuError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel10.setText("Mã nhân viên");

        jLabel11.setText("Tên nhân viên");

        jLabel12.setText("Tên đệm nhân viên");

        jLabel13.setText("Họ nhân viên");

        jLabel14.setText("Giới tính");

        jLabel15.setText("Ngày sinh");

        jLabel16.setText("Địa chỉ");

        jLabel17.setText("Mật khẩu");

        jLabel18.setText("Cửa hàng");

        jLabel19.setText("Chức vụ");

        jLabel20.setText("Gửi BC");

        jLabel21.setText("Trạng thái");

        buttonGroup1.add(rdViewNhanVienNam);
        rdViewNhanVienNam.setText("Nam");

        buttonGroup1.add(rdViewNhanVienNu);
        rdViewNhanVienNu.setText("Nữ");

        cbbViewNhanVienCH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbViewNhanVienCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbViewNhanVienTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbViewNhanVienGuiBC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtViewNhanVienMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewNhanVienTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewNhanVienTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewNhanVienHoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rdViewNhanVienNam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdViewNhanVienNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbViewNhanVienGuiBC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwViewNhanVienPass))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbViewNhanVienCH, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbViewNhanVienCV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbViewNhanVienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateViewNhanVienNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewNhanVienDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(231, 231, 231))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel15)
                        .addComponent(txtViewNhanVienMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateViewNhanVienNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(txtViewNhanVienTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewNhanVienDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(txtViewNhanVienTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwViewNhanVienPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(txtViewNhanVienHoNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbViewNhanVienCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel19)
                        .addComponent(cbbViewNhanVienCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdViewNhanVienNam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdViewNhanVienNu)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(cbbViewNhanVienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbViewNhanVienGuiBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnViewNhanVienSave.setText("Thêm");

        btnViewNhanVienUpdate.setText("Sửa");

        btnViewNhanVienDelete.setText("Xóa");

        btnViewNhanVienReset.setText("Reset");
        btnViewNhanVienReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNhanVienResetActionPerformed(evt);
            }
        });

        jlViewNhanVienError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlViewNhanVienError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewNhanVienError.setText("jLabel8");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Mật khẩu", "Cửa hàng", "Chức vụ", "Gửi BC", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlViewNhanVienError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnViewNhanVienSave)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnViewNhanVienUpdate)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnViewNhanVienDelete)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnViewNhanVienReset))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 147, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewNhanVienSave)
                    .addComponent(btnViewNhanVienUpdate)
                    .addComponent(btnViewNhanVienDelete)
                    .addComponent(btnViewNhanVienReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlViewNhanVienError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý nhân viên", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cửa hàng"));

        jLabel3.setText("Mã cửa hàng");

        jLabel4.setText("Tên cửa hàng");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Thành Phố");

        jLabel7.setText("Quốc gia");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCuaHangQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCuaHangThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCuaHangDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCuaHangTenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewCuaHangMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtViewCuaHangMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtViewCuaHangTenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtViewCuaHangDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtViewCuaHangThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtViewCuaHangQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btntxtViewCuaHangSave.setText("Thêm");
        btntxtViewCuaHangSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntxtViewCuaHangSaveActionPerformed(evt);
            }
        });

        btnViewCuaHangUpdate.setText("Sửa");
        btnViewCuaHangUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCuaHangUpdateActionPerformed(evt);
            }
        });

        btnViewCuaHangDelete.setText("Xóa");
        btnViewCuaHangDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCuaHangDeleteActionPerformed(evt);
            }
        });

        btnViewCuaHangReset.setText("Reset");
        btnViewCuaHangReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCuaHangResetActionPerformed(evt);
            }
        });

        tblCuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã cửa hàng", "Tên cửa hàng", "Địa chỉ", "Thành phố", "Quốc gia"
            }
        ));
        tblCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuaHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCuaHang);

        jlViewCuaHangError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlViewCuaHangError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewCuaHangError.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btntxtViewCuaHangSave)
                                    .addComponent(btnViewCuaHangUpdate)
                                    .addComponent(btnViewCuaHangDelete)
                                    .addComponent(btnViewCuaHangReset))
                                .addGap(0, 341, Short.MAX_VALUE))
                            .addComponent(jlViewCuaHangError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btntxtViewCuaHangSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCuaHangUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCuaHangDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCuaHangReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jlViewCuaHangError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý cửa hàng", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chức vụ"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã chức vụ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên chức vụ:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnViewChucVuAdd.setText("Thêm");
        btnViewChucVuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChucVuAddActionPerformed(evt);
            }
        });

        btnViewChucVuReset.setText("Reset");
        btnViewChucVuReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChucVuResetActionPerformed(evt);
            }
        });

        btnViewChucVuUpdate.setText("Sửa");
        btnViewChucVuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChucVuUpdateActionPerformed(evt);
            }
        });

        btnViewChucVuDelete.setText("Xóa");
        btnViewChucVuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChucVuDeleteActionPerformed(evt);
            }
        });

        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã chức vụ", "Tên chức vụ"
            }
        ));
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucVu);

        jlViewChucVuError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlViewChucVuError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewChucVuError.setText("jLabel8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlViewChucVuError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewChucVuAdd)
                            .addComponent(btnViewChucVuReset)
                            .addComponent(btnViewChucVuDelete)
                            .addComponent(btnViewChucVuUpdate))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnViewChucVuAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewChucVuUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewChucVuReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewChucVuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jlViewChucVuError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý chức vụ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewNhanVienResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNhanVienResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewNhanVienResetActionPerformed

    private void btnViewChucVuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChucVuDeleteActionPerformed
        // TODO add your handling code here:
        String check = CHUC_VU_SERVICE.delete(listChucVu.get(checkchucVu));
        if (!check.equals("")) {
            jlViewChucVuError.setText(check);
            return;
        }
        resetFormChucVu();
        listChucVu = CHUC_VU_SERVICE.getList();
        getTableChucVu(listChucVu);
        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
    }//GEN-LAST:event_btnViewChucVuDeleteActionPerformed

    private void btnViewChucVuResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChucVuResetActionPerformed
        // TODO add your handling code here:
        resetFormChucVu();
    }//GEN-LAST:event_btnViewChucVuResetActionPerformed

    private void btnViewChucVuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChucVuAddActionPerformed
        // TODO add your handling code here:
        ChucVuViewModel chucVu = insertDataChucVu();
        if (chucVu == null) {
            return;
        }
        String check = CHUC_VU_SERVICE.save(chucVu);
        if (!check.equals("")) {
            jlViewChucVuError.setText(check);
            return;
        }
        resetFormChucVu();
        listChucVu = CHUC_VU_SERVICE.getList();
        getTableChucVu(listChucVu);
        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
    }//GEN-LAST:event_btnViewChucVuAddActionPerformed

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        // TODO add your handling code here:
        checkchucVu = tblChucVu.getSelectedRow();
        fillFormChucVu(checkchucVu);
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void btnViewChucVuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChucVuUpdateActionPerformed
        // TODO add your handling code here:
        ChucVuViewModel chucVu = insertDataChucVu();
        if (chucVu == null) {
            return;
        }
        String check = CHUC_VU_SERVICE.update(chucVu);
        if (!check.equals("")) {
            jlViewChucVuError.setText(check);
            return;
        }
        resetFormChucVu();
        listChucVu = CHUC_VU_SERVICE.getList();
        getTableChucVu(listChucVu);
        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
    }//GEN-LAST:event_btnViewChucVuUpdateActionPerformed

    private void btntxtViewCuaHangSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntxtViewCuaHangSaveActionPerformed
        // TODO add your handling code here:
        CuaHangViewModel cuaHangViewModel = insertDataCuaHang();
        if (cuaHangViewModel == null) {
            return;
        }
        String check = CUA_HANG_SERVICE.save(cuaHangViewModel);
        if (!check.equals("")) {
            jlViewCuaHangError.setText(check);
            return;
        }
        listCuaHang = CUA_HANG_SERVICE.getList();
        getTableCuaHang(listCuaHang);
        resetFormCuaHang();
        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
    }//GEN-LAST:event_btntxtViewCuaHangSaveActionPerformed

    private void tblCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuaHangMouseClicked
        // TODO add your handling code here:
        checkCuaHang = tblCuaHang.getSelectedRow();
        fillFormCuaHang(checkCuaHang);
    }//GEN-LAST:event_tblCuaHangMouseClicked

    private void btnViewCuaHangUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCuaHangUpdateActionPerformed
        // TODO add your handling code here:
        CuaHangViewModel cuaHangViewModel = insertDataCuaHang();
        if (cuaHangViewModel == null) {
            return;
        }
        String check = CUA_HANG_SERVICE.update(cuaHangViewModel);
        if (!check.equals("")) {
            jlViewCuaHangError.setText(check);
            return;
        }
        listCuaHang = CUA_HANG_SERVICE.getList();
        getTableCuaHang(listCuaHang);
        resetFormCuaHang();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
    }//GEN-LAST:event_btnViewCuaHangUpdateActionPerformed

    private void btnViewCuaHangResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCuaHangResetActionPerformed
        // TODO add your handling code here:
        resetFormCuaHang();
    }//GEN-LAST:event_btnViewCuaHangResetActionPerformed

    private void btnViewCuaHangDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCuaHangDeleteActionPerformed
        // TODO add your handling code here:
        CuaHangViewModel cuaHangViewModel = listCuaHang.get(checkCuaHang);
        String check = CUA_HANG_SERVICE.delete(cuaHangViewModel);
        if (!check.equals("")) {
            jlViewCuaHangError.setText(check);
            return;
        }
        listCuaHang = CUA_HANG_SERVICE.getList();
        getTableCuaHang(listCuaHang);
        resetFormCuaHang();
        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
    }//GEN-LAST:event_btnViewCuaHangDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewChucVuAdd;
    private javax.swing.JButton btnViewChucVuDelete;
    private javax.swing.JButton btnViewChucVuReset;
    private javax.swing.JButton btnViewChucVuUpdate;
    private javax.swing.JButton btnViewCuaHangDelete;
    private javax.swing.JButton btnViewCuaHangReset;
    private javax.swing.JButton btnViewCuaHangUpdate;
    private javax.swing.JButton btnViewNhanVienDelete;
    private javax.swing.JButton btnViewNhanVienReset;
    private javax.swing.JButton btnViewNhanVienSave;
    private javax.swing.JButton btnViewNhanVienUpdate;
    private javax.swing.JButton btntxtViewCuaHangSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbViewNhanVienCH;
    private javax.swing.JComboBox<String> cbbViewNhanVienCV;
    private javax.swing.JComboBox<String> cbbViewNhanVienGuiBC;
    private javax.swing.JComboBox<String> cbbViewNhanVienTT;
    private com.toedter.calendar.JDateChooser dateViewNhanVienNgaySinhNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlViewChucVuError;
    private javax.swing.JLabel jlViewCuaHangError;
    private javax.swing.JLabel jlViewNhanVienError;
    private javax.swing.JPasswordField pwViewNhanVienPass;
    private javax.swing.JRadioButton rdViewNhanVienNam;
    private javax.swing.JRadioButton rdViewNhanVienNu;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTable tblCuaHang;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtMaChucVu;
    private javax.swing.JTextField txtTenChucVu;
    private javax.swing.JTextField txtViewCuaHangDiaChi;
    private javax.swing.JTextField txtViewCuaHangMaCuaHang;
    private javax.swing.JTextField txtViewCuaHangQuocGia;
    private javax.swing.JTextField txtViewCuaHangTenCuaHang;
    private javax.swing.JTextField txtViewCuaHangThanhPho;
    private javax.swing.JTextField txtViewNhanVienDiaChi;
    private javax.swing.JTextField txtViewNhanVienHoNV;
    private javax.swing.JTextField txtViewNhanVienMaNV;
    private javax.swing.JTextField txtViewNhanVienTenDem;
    private javax.swing.JTextField txtViewNhanVienTenNV;
    // End of variables declaration//GEN-END:variables
private void getTableChucVu(List<ChucVuViewModel> list) {
        modelViewChucVu.setRowCount(0);
        list.forEach((t) -> {
            modelViewChucVu.addRow(t.getObj(modelViewChucVu.getRowCount() + 1));
        });
    }

    private ChucVuViewModel insertDataChucVu() {
        jlViewChucVuError.setText("");
        String ma = txtMaChucVu.getText();
        String ten = txtTenChucVu.getText();
        if (!Validate.checkEmtry(ten, ma)) {
            jlViewChucVuError.setText("Không để trống dữ liệu");
            return null;
        }
        return ChucVuViewModel.builder().ma(ma).id(idChucVu).ten(ten).build();
    }

    private void resetFormChucVu() {
        txtMaChucVu.setText("");
        txtTenChucVu.setText("");
        idChucVu = "";
        checkchucVu = -1;
        jlViewChucVuError.setText("");
        btnViewChucVuDelete.setEnabled(false);
        btnViewChucVuUpdate.setEnabled(false);
        tblChucVu.clearSelection();
    }

    private void fillFormChucVu(int checkchucVu) {
        ChucVuViewModel cv = listChucVu.get(checkchucVu);
        idChucVu = cv.getId();
        txtMaChucVu.setText(cv.getMa());
        txtTenChucVu.setText(cv.getTen());
        btnViewChucVuDelete.setEnabled(true);
        btnViewChucVuUpdate.setEnabled(true);
    }

    private void getTableCuaHang(List<CuaHangViewModel> list) {
        modelViewCuaHang.setRowCount(0);
        list.forEach((t) -> {
            modelViewCuaHang.addRow(t.getObj(modelViewChucVu.getRowCount() + 1));
        });
    }

    private CuaHangViewModel insertDataCuaHang() {
        jlViewCuaHangError.setText("");
        String ma = txtViewCuaHangMaCuaHang.getText();
        String ten = txtViewCuaHangTenCuaHang.getText();
        String diaChi = txtViewCuaHangDiaChi.getText();
        String thanhPho = txtViewCuaHangThanhPho.getText();
        String quocGia = txtViewCuaHangQuocGia.getText();
        if (!Validate.checkEmtry(ma, ten, diaChi, thanhPho, quocGia)) {
            jlViewCuaHangError.setText("Không để trống dữ liệu");
            return null;
        }
        return CuaHangViewModel.builder().id(idCuaHang).ma(ma).ten(ten).diaChi(diaChi).thanhPho(thanhPho).quocGia(quocGia).build();
    }

    private void resetFormCuaHang() {
        txtViewCuaHangMaCuaHang.setText("");
        txtViewCuaHangTenCuaHang.setText("");
        txtViewCuaHangDiaChi.setText("");
        txtViewCuaHangThanhPho.setText("");
        txtViewCuaHangQuocGia.setText("");
        idCuaHang = "";
        checkCuaHang = -1;
        jlViewCuaHangError.setText("");
        btnViewCuaHangDelete.setEnabled(false);
        btnViewCuaHangUpdate.setEnabled(false);
        tblCuaHang.clearSelection();
    }

    private void fillFormCuaHang(int checkCuaHang) {
        CuaHangViewModel ch = listCuaHang.get(checkCuaHang);
        txtViewCuaHangMaCuaHang.setText(ch.getMa());
        txtViewCuaHangTenCuaHang.setText(ch.getTen());
        txtViewCuaHangDiaChi.setText(ch.getDiaChi());
        txtViewCuaHangThanhPho.setText(ch.getThanhPho());
        txtViewCuaHangQuocGia.setText(ch.getQuocGia());
        idCuaHang = ch.getId();
        btnViewCuaHangDelete.setEnabled(true);
        btnViewCuaHangUpdate.setEnabled(true);
    }

    private void getCbb() {
        boxModelChucVu.removeAllElements();
        boxModelCuaHang.removeAllElements();
        boxModelGuiBC.removeAllElements();
        boxModelChucVu.addAll(CHUC_VU_SERVICE.getList());
        boxModelCuaHang.addAll(CUA_HANG_SERVICE.getList());
        boxModelGuiBC.addAll(NHAN_VIEN_SERVICE.getListGuiBC());
    }

    private NhanVienViewModel insertDataNhanVien() {
        String ma = txtViewNhanVienMaNV.getText();
        String ho = txtViewNhanVienHoNV.getText();
        String tenDem = txtViewNhanVienTenDem.getText();
        String ten = txtViewNhanVienTenNV.getText();
        String diaChi = txtViewNhanVienDiaChi.getText();
        String pass = new String(pwViewNhanVienPass.getPassword());
        ChucVuViewModel chucVuViewModel = (ChucVuViewModel) cbbViewNhanVienCV.getSelectedItem();
        CuaHangViewModel cuaHangViewModel = (CuaHangViewModel) cbbViewNhanVienCH.getSelectedItem();
        NhanVienViewModel guiBC = (NhanVienViewModel) cbbViewNhanVienGuiBC.getSelectedItem();
        Date ngaySinh = dateViewNhanVienNgaySinhNV.getDate();
        String gioiTinh = rdViewNhanVienNam.isSelected() ? "Nam" : "Nữ";
        TrangThaiNhanVien trangThaiNhanVien = cbbViewNhanVienTT.getSelectedItem().toString().equals("Đang làm việc") ? TrangThaiNhanVien.DANG_LAM_VIEC : TrangThaiNhanVien.DANG_NGHI;
        if (Validate.checkEmtry(ma, ho, ten, tenDem, diaChi, pass)) {
            jlViewNhanVienError.setText("Không để trống dữ liệu");
            return null;
        }
        if (chucVuViewModel == null || cuaHangViewModel == null || ngaySinh == null || (!rdViewNhanVienNam.isSelected() && !rdViewNhanVienNu.isSelected())) {
            jlViewNhanVienError.setText("Không để trống dữ liệu");
            return null;
        }
        if (!Validate.checkString(ten, tenDem, ho)) {
            jlViewNhanVienError.setText("Họ,tên đệm,tên nhân viên không hợp lệ");
            return null;
        }
        
    }
}
