/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duanmaujava.Views;

import com.mycompany.duanmaujava.DomainModels.ChiTietSanPham;
import com.mycompany.duanmaujava.DomainModels.DongSP;
import com.mycompany.duanmaujava.DomainModels.MauSac;
import com.mycompany.duanmaujava.DomainModels.NhaSanXuat;
import com.mycompany.duanmaujava.DomainModels.SanPham;
import com.mycompany.duanmaujava.Services.ChiTietHoaDonService;
import com.mycompany.duanmaujava.Services.ChiTietSanPhamService;
import com.mycompany.duanmaujava.Services.DongSanPhamService;
import com.mycompany.duanmaujava.Services.MauSacService;
import com.mycompany.duanmaujava.Services.NhaSanXuatService;
import com.mycompany.duanmaujava.Services.SanPhamService;
import com.mycompany.duanmaujava.Services.impl.ChiTietSanPhamServiceImpl;
import com.mycompany.duanmaujava.Services.impl.DongSanPhamServiceImpl;
import com.mycompany.duanmaujava.Services.impl.HoaDonChiTietServiceImpl;
import com.mycompany.duanmaujava.Services.impl.MauSacServiceImpl;
import com.mycompany.duanmaujava.Services.impl.NhaSanXuatServiceImpl;
import com.mycompany.duanmaujava.Services.impl.SanPhamServiceImpl;
import com.mycompany.duanmaujava.Utilities.Validate;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class ViewQuanLyThongTinSanPham extends javax.swing.JFrame {

    /**
     * Creates new form ViewChiTietSanPham
     */
    DefaultTableModel modelChiTietSanPham;
    DefaultTableModel modelSanPham;
    DefaultTableModel modelNhaSanXuat;
    DefaultTableModel modelMauSac;
    DefaultTableModel modelDongSanPham;
    private List<ChiTietSanPham> listChiTietSanPhams = new ArrayList<>();
    private List<SanPham> listSanPhams = new ArrayList<>();
    private List<NhaSanXuat> listNhaSanXuats = new ArrayList<>();
    private List<MauSac> listMauSacs = new ArrayList<>();
    private List<DongSP> listDongSPs = new ArrayList<>();
    private static final ChiTietSanPhamService CHI_TIET_SAN_PHAM_SERVICE = new ChiTietSanPhamServiceImpl();
    private static final DongSanPhamService DONG_SAN_PHAM_SERVICE = new DongSanPhamServiceImpl();
    private static final MauSacService MAU_SAC_SERVICE = new MauSacServiceImpl();
    private static final NhaSanXuatService NHA_SAN_XUAT_SERVICE = new NhaSanXuatServiceImpl();
    private static final SanPhamService SAN_PHAM_SERVICE = new SanPhamServiceImpl();
    private static final ChiTietHoaDonService CHI_TIET_HOA_DON_SERVICE = new HoaDonChiTietServiceImpl();
    DefaultComboBoxModel boxModelDongSP;
    DefaultComboBoxModel boxModelMauSac;
    DefaultComboBoxModel boxModelNhaSX;
    DefaultComboBoxModel boxModelSanPham;
    private int check;
    private ChiTietSanPham ctspCheck = new ChiTietSanPham();
    private String id;
    private String idSanPham, idNSX, idDongSP, idMauSac;
    private int checkViewSP, checkViewDongSP, checkViewNSX, checkViewMauSac;

    public ViewQuanLyThongTinSanPham() {
        initComponents();
        modelChiTietSanPham = (DefaultTableModel) btlChiTietSP.getModel();
        modelSanPham = (DefaultTableModel) tblSanPham.getModel();
        modelDongSanPham = (DefaultTableModel) tblDongSanPham.getModel();
        modelMauSac = (DefaultTableModel) tblMauSac.getModel();
        modelNhaSanXuat = (DefaultTableModel) tblNhSanXuat.getModel();
        boxModelDongSP = (DefaultComboBoxModel) cbDongSP.getModel();
        boxModelMauSac = (DefaultComboBoxModel) cbMauSac.getModel();
        boxModelNhaSX = (DefaultComboBoxModel) cbNhaSanXuat.getModel();
        boxModelSanPham = (DefaultComboBoxModel) cbSanPham.getModel();
        getCbb();
        listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getList());
        listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getList());
        listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getList());
        listMauSacs = getListMauSac(MAU_SAC_SERVICE.getList());
        listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getList());
        jlError.setText("");
        jlViewSanPhamError.setText("");
        jlSearchErrors.setText("");
        jlViewDongSanPhamError.setText("");
        jlViewMauSacError.setText("");
        jlViewNSXError.setText("");
        resetForm();
        resetFormViewSanPham();
        resetFormViewDongSP();
        resetFormViewMauSac();
        resetFormViewNhaSanxuat();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDongSP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMauSac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbNhaSanXuat = new javax.swing.JComboBox<>();
        jsNamBH = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbSanPham = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlChiTietSP = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jlSearchErrors = new javax.swing.JLabel();
        jlError = new javax.swing.JLabel();
        btnResetCTSP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnViewSanPhamUpdate = new javax.swing.JButton();
        btnViewSanPhamDelete = new javax.swing.JButton();
        txtViewSanPhamSreach = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jlViewSanPhamError = new javax.swing.JLabel();
        btnResetSP = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhSanXuat = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtViewNSXMaNSX = new javax.swing.JTextField();
        txtViewNSXTenNSX = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnViewNSXUpdate = new javax.swing.JButton();
        btnViewNSXDelete = new javax.swing.JButton();
        txtViewNSXSreach = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jlViewNSXError = new javax.swing.JLabel();
        btnResetNSX = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMauSac = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtViewMauSacMaMau = new javax.swing.JTextField();
        txtViewMauSacTenMau = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btnViewMauSacUpdate = new javax.swing.JButton();
        btnViewMauSacDelete = new javax.swing.JButton();
        txtViewMauSacSearch = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jlViewMauSacError = new javax.swing.JLabel();
        btnResetMS = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDongSanPham = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtViewDongSPMaDongSP = new javax.swing.JTextField();
        txtViewDongSPTenDongSP = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnViewDongSanPhamUpdate = new javax.swing.JButton();
        btnViewDongSanPhamDelete = new javax.swing.JButton();
        txtViewDongSanPhamSreach = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jlViewDongSanPhamError = new javax.swing.JLabel();
        btnResetDSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết sản phẩm"));

        jLabel1.setText(" Sản phẩm");

        jLabel2.setText("Dòng sản phẩm");

        cbDongSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Màu sắc");

        cbMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Nhà sản xuất");

        cbNhaSanXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jsNamBH.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsNamBHStateChanged(evt);
            }
        });

        jLabel5.setText("Năm bảo hành");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("năm");

        jLabel7.setText("Mô tả");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        jLabel8.setText("Số lượng tồn");

        jLabel9.setText("Giá Nhập");

        jLabel10.setText("Giá Bán");

        jLabel13.setText("VNĐ");

        jLabel14.setText("VNĐ");

        cbSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbDongSP, 0, 156, Short.MAX_VALUE)
                        .addComponent(cbNhaSanXuat, 0, 156, Short.MAX_VALUE)
                        .addComponent(cbMauSac, 0, 156, Short.MAX_VALUE)
                        .addComponent(cbSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jsNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel1))
                            .addComponent(cbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        btlChiTietSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Nhà sản xuất", "Màu sắc", "Dòng sản phẩm", "Năm bảo hành", "Mô tả", "Số lượng tồn", "Giá nhập", "Gián bán"
            }
        ));
        btlChiTietSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlChiTietSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(btlChiTietSP);
        if (btlChiTietSP.getColumnModel().getColumnCount() > 0) {
            btlChiTietSP.getColumnModel().getColumn(10).setResizable(false);
        }

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel12.setText("Nhập tên sản phẩm cần tìm");

        jlSearchErrors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlSearchErrors.setForeground(new java.awt.Color(255, 0, 0));
        jlSearchErrors.setText("......");

        jlError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 0, 0));
        jlError.setText("jLabel15");

        btnResetCTSP.setText("Reset");
        btnResetCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCTSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(btnResetCTSP))
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlSearchErrors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlError, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(jButton2)
                    .addComponent(btnDelete)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlSearchErrors)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnResetCTSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jlError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý chi tiết sản phẩm", jPanel3);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã sản phẩm");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tên sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnViewSanPhamUpdate.setText("Sửa");
        btnViewSanPhamUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSanPhamUpdateActionPerformed(evt);
            }
        });

        btnViewSanPhamDelete.setText("Xóa");
        btnViewSanPhamDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSanPhamDeleteActionPerformed(evt);
            }
        });

        txtViewSanPhamSreach.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtViewSanPhamSreachCaretUpdate(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Nhập tên sản phẩm");

        jlViewSanPhamError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlViewSanPhamError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewSanPhamError.setText("jLabel17");

        btnResetSP.setText("Reset");
        btnResetSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewSanPhamSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewSanPhamUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewSanPhamDelete))
                        .addComponent(jlViewSanPhamError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnResetSP))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnViewSanPhamUpdate)
                            .addComponent(btnViewSanPhamDelete))
                        .addGap(18, 18, 18)
                        .addComponent(btnResetSP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtViewSanPhamSreach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlViewSanPhamError))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý sản phẩm ", jPanel2);

        tblNhSanXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên"
            }
        ));
        tblNhSanXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhSanXuatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNhSanXuat);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà sản xuất"));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Mã nhà sản xuất");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tên nhà sản xuất");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewNSXMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewNSXTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtViewNSXMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtViewNSXTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnViewNSXUpdate.setText("Sửa");
        btnViewNSXUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNSXUpdateActionPerformed(evt);
            }
        });

        btnViewNSXDelete.setText("Xóa");
        btnViewNSXDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNSXDeleteActionPerformed(evt);
            }
        });

        txtViewNSXSreach.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtViewNSXSreachCaretUpdate(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Tìm theo tên NSX");

        jlViewNSXError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlViewNSXError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewNSXError.setText("jLabel17");

        btnResetNSX.setText("Reset");
        btnResetNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNSXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewNSXSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewNSXUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewNSXDelete))
                        .addComponent(jlViewNSXError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnResetNSX))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btnViewNSXUpdate)
                            .addComponent(btnViewNSXDelete))
                        .addGap(18, 18, 18)
                        .addComponent(btnResetNSX))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewNSXSreach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlViewNSXError)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý NSX ", jPanel5);

        tblMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên"
            }
        ));
        tblMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauSacMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMauSac);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin màu sắc"));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Mã màu");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Tên màu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewMauSacMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewMauSacTenMau, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtViewMauSacMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtViewMauSacTenMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnViewMauSacUpdate.setText("Sửa");
        btnViewMauSacUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMauSacUpdateActionPerformed(evt);
            }
        });

        btnViewMauSacDelete.setText("Xóa");
        btnViewMauSacDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMauSacDeleteActionPerformed(evt);
            }
        });

        txtViewMauSacSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtViewMauSacSearchCaretUpdate(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Nhập tên màu");

        jlViewMauSacError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlViewMauSacError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewMauSacError.setText("jLabel17");

        btnResetMS.setText("Reset");
        btnResetMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewMauSacSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewMauSacUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewMauSacDelete))
                        .addComponent(jlViewMauSacError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnResetMS))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btnViewMauSacUpdate)
                            .addComponent(btnViewMauSacDelete))
                        .addGap(28, 28, 28)
                        .addComponent(btnResetMS))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewMauSacSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlViewMauSacError)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý Màu sắc ", jPanel7);

        tblDongSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên"
            }
        ));
        tblDongSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDongSanPhamMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDongSanPham);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin dòng sản phẩm"));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Mã dòng sản phẩm");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Tên dòng sản phẩm");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewDongSPTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txtViewDongSPMaDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(154, 154, 154))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtViewDongSPMaDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtViewDongSPTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnViewDongSanPhamUpdate.setText("Sửa");
        btnViewDongSanPhamUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDongSanPhamUpdateActionPerformed(evt);
            }
        });

        btnViewDongSanPhamDelete.setText("Xóa");
        btnViewDongSanPhamDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDongSanPhamDeleteActionPerformed(evt);
            }
        });

        txtViewDongSanPhamSreach.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtViewDongSanPhamSreachCaretUpdate(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Nhập tên dòng sản phẩm");

        jlViewDongSanPhamError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlViewDongSanPhamError.setForeground(new java.awt.Color(255, 0, 0));
        jlViewDongSanPhamError.setText("jLabel17");

        btnResetDSP.setText("Reset");
        btnResetDSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewDongSanPhamSreach, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewDongSanPhamUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(btnViewDongSanPhamDelete))
                        .addComponent(jlViewDongSanPhamError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnResetDSP))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(btnViewDongSanPhamUpdate)
                            .addComponent(btnViewDongSanPhamDelete))
                        .addGap(18, 18, 18)
                        .addComponent(btnResetDSP))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViewDongSanPhamSreach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jlViewDongSanPhamError))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý dòng sản phẩm", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewSanPhamSreachCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtViewSanPhamSreachCaretUpdate
        // TODO add your handling code here:
        jlViewSanPhamError.setText("");
        if (!"".equals(txtViewSanPhamSreach.getText())) {
            listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getListByTen(txtViewSanPhamSreach.getText()));
            if (tblSanPham.getRowCount() == 0) {
                jlViewSanPhamError.setText("Không có dữ liệu");
            }
        } else {
            listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getList());
        }
    }//GEN-LAST:event_txtViewSanPhamSreachCaretUpdate

    private void btnViewSanPhamDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSanPhamDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa sản phẩm dã chọn ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String check = SAN_PHAM_SERVICE.delete(listSanPhams.get(checkViewSP));
            if (!check.equals("")) {
                JOptionPane.showMessageDialog(rootPane, check);
                return;
            }
            listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getList());
            resetFormViewSanPham();
            JOptionPane.showMessageDialog(rootPane, "Xóa sản phẩm thành công");
        } else {
            return;
        }
    }//GEN-LAST:event_btnViewSanPhamDeleteActionPerformed

    private void btnViewSanPhamUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSanPhamUpdateActionPerformed
        // TODO add your handling code here:
        SanPham sanPham = insertDataViewSanPham();
        if (sanPham == null) {
            return;
        }
        String check = SAN_PHAM_SERVICE.update(sanPham);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getList());
        resetFormViewSanPham();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật sản phẩm thành công");
    }//GEN-LAST:event_btnViewSanPhamUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SanPham sanPham = insertDataViewSanPham();
        if (sanPham == null) {
            return;
        }
        String check = SAN_PHAM_SERVICE.save(sanPham);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listSanPhams = getListSanPham(SAN_PHAM_SERVICE.getList());
        resetFormViewSanPham();
        JOptionPane.showMessageDialog(rootPane, "Thêm sản phẩm thành công");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        checkViewSP = tblSanPham.getSelectedRow();
        fillFormSanPham(listSanPhams.get(checkViewSP));
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        // TODO add your handling code here:
        jlSearchErrors.setText("");
        if (!"".equals(txtSearch.getText())) {
            listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getByTenSP(txtSearch.getText()));
            if (btlChiTietSP.getRowCount() == 0) {
                jlSearchErrors.setText("Không có dữ liệu");
            }
        } else {
            listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getList());
        }
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa sản phẩm dã chọn ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String check = CHI_TIET_SAN_PHAM_SERVICE.delete(ctspCheck);
            if (!check.equals("")) {
                JOptionPane.showMessageDialog(rootPane, check);
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Xóa sản phẩm thành công");
            listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getList());
            resetForm();
        } else {
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ctspCheck = insertData();
        if (ctspCheck == null) {
            return;
        }
        String check = CHI_TIET_SAN_PHAM_SERVICE.save(ctspCheck);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getList());
        resetForm();
        ctspCheck = null;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ctspCheck = insertData();
        if (ctspCheck == null) {
            ctspCheck = listChiTietSanPhams.get(check);
            return;
        }
        CHI_TIET_SAN_PHAM_SERVICE.updateChiTietSanPham(ctspCheck);
        JOptionPane.showMessageDialog(rootPane, "cập nhật thành công");
        listChiTietSanPhams = getListChiTietSanPham(CHI_TIET_SAN_PHAM_SERVICE.getList());
        resetForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btlChiTietSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlChiTietSPMouseClicked
        // TODO add your handling code here:
        check = btlChiTietSP.getSelectedRow();
        ctspCheck = listChiTietSanPhams.get(check);
        id = ctspCheck.getId();
        idSanPham = ctspCheck.getSanPham().getId();
        fillForm(ctspCheck);
    }//GEN-LAST:event_btlChiTietSPMouseClicked

    private void jsNamBHStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsNamBHStateChanged
        // TODO add your handling code here:
        if (Integer.parseInt(jsNamBH.getValue().toString()) < 0) {
            JOptionPane.showMessageDialog(rootPane, "Không được nhỏ hơn 0");
            jsNamBH.setValue(0);
        }
        if (Integer.parseInt(jsNamBH.getValue().toString()) > 20) {
            JOptionPane.showMessageDialog(rootPane, "Không được lớn hơn 20");
            jsNamBH.setValue(0);
        }
    }//GEN-LAST:event_jsNamBHStateChanged

    private void tblNhSanXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhSanXuatMouseClicked
        // TODO add your handling code here:
        checkViewNSX = tblNhSanXuat.getSelectedRow();
        fillFormNSX(listNhaSanXuats.get(checkViewNSX));
    }//GEN-LAST:event_tblNhSanXuatMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NhaSanXuat nhaSanXuat = insertDataViewNhaSanXuat();
        if (nhaSanXuat == null) {
            return;
        }
        String check = NHA_SAN_XUAT_SERVICE.save(nhaSanXuat);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getList());
        resetFormViewNhaSanxuat();
        JOptionPane.showMessageDialog(rootPane, "Thêm nhà sản xuất thành công");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnViewNSXUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNSXUpdateActionPerformed
        // TODO add your handling code here:
        NhaSanXuat nhaSanXuat = insertDataViewNhaSanXuat();
        if (nhaSanXuat == null) {
            return;
        }
        String check = NHA_SAN_XUAT_SERVICE.update(nhaSanXuat);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getList());
        resetFormViewNhaSanxuat();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật nhà sản xuất thành công");

    }//GEN-LAST:event_btnViewNSXUpdateActionPerformed

    private void btnViewNSXDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNSXDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa nhà sản xuất đã chọn ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String check = NHA_SAN_XUAT_SERVICE.delete(listNhaSanXuats.get(checkViewNSX));
            if (!check.equals("")) {
                JOptionPane.showMessageDialog(rootPane, check);
                return;
            }
            listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getList());
            resetFormViewNhaSanxuat();
            JOptionPane.showMessageDialog(rootPane, "Xóa nhà sản xuất thành công");
        } else {
            return;
        }
    }//GEN-LAST:event_btnViewNSXDeleteActionPerformed

    private void txtViewNSXSreachCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtViewNSXSreachCaretUpdate
        // TODO add your handling code here:
        jlViewNSXError.setText("");
        if (!"".equals(txtViewNSXSreach.getText())) {
            listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getListByTen(txtViewNSXSreach.getText()));
            if (tblNhSanXuat.getRowCount() == 0) {
                jlViewNSXError.setText("Không có dữ liệu");
            }
        } else {
            listNhaSanXuats = getListNhaSanXuat(NHA_SAN_XUAT_SERVICE.getList());
        }
    }//GEN-LAST:event_txtViewNSXSreachCaretUpdate

    private void tblMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMauSacMouseClicked
        // TODO add your handling code here:
        checkViewMauSac = tblMauSac.getSelectedRow();
        fillFormMauSac(listMauSacs.get(checkViewMauSac));
    }//GEN-LAST:event_tblMauSacMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MauSac mauSac = insertDataViewMauSac();
        if (mauSac == null) {
            return;
        }
        String check = MAU_SAC_SERVICE.save(mauSac);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listMauSacs = getListMauSac(MAU_SAC_SERVICE.getList());
        resetFormViewMauSac();
        JOptionPane.showMessageDialog(rootPane, "Thêm màu sắc thành công");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnViewMauSacUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMauSacUpdateActionPerformed
        // TODO add your handling code here:
        MauSac mauSac = insertDataViewMauSac();
        if (mauSac == null) {
            return;
        }
        String check = MAU_SAC_SERVICE.update(mauSac);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listMauSacs = getListMauSac(MAU_SAC_SERVICE.getList());
        resetFormViewMauSac();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật màu sắc thành công");
    }//GEN-LAST:event_btnViewMauSacUpdateActionPerformed

    private void btnViewMauSacDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMauSacDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa màu sắc đã chọn ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String check = MAU_SAC_SERVICE.delete(listMauSacs.get(checkViewMauSac));
            if (!check.equals("")) {
                JOptionPane.showMessageDialog(rootPane, check);
                return;
            }
            listMauSacs = getListMauSac(MAU_SAC_SERVICE.getList());
            resetFormViewMauSac();
            JOptionPane.showMessageDialog(rootPane, "Xóa màu sắc thành công");
        } else {
            return;
        }
    }//GEN-LAST:event_btnViewMauSacDeleteActionPerformed

    private void txtViewMauSacSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtViewMauSacSearchCaretUpdate
        // TODO add your handling code here:
        jlViewMauSacError.setText("");
        if (!"".equals(txtViewMauSacSearch.getText())) {
            listMauSacs = getListMauSac(MAU_SAC_SERVICE.getListByTen(txtViewMauSacSearch.getText()));
            if (tblMauSac.getRowCount() == 0) {
                jlViewMauSacError.setText("Không có dữ liệu");
            }
        } else {
            listMauSacs = getListMauSac(MAU_SAC_SERVICE.getList());
        }
    }//GEN-LAST:event_txtViewMauSacSearchCaretUpdate

    private void tblDongSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDongSanPhamMouseClicked
        // TODO add your handling code here:
        checkViewDongSP = tblDongSanPham.getSelectedRow();
        fillFormDongSP(listDongSPs.get(checkViewDongSP));
    }//GEN-LAST:event_tblDongSanPhamMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DongSP dongSP = insertDataViewDongSP();
        if (dongSP == null) {
            return;
        }
        String check = DONG_SAN_PHAM_SERVICE.save(dongSP);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getList());
        resetFormViewDongSP();
        JOptionPane.showMessageDialog(rootPane, "Thêm dòng sản phẩm thành công");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnViewDongSanPhamUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDongSanPhamUpdateActionPerformed
        // TODO add your handling code here:
        DongSP dongSP = insertDataViewDongSP();
        if (dongSP == null) {
            return;
        }
        String check = DONG_SAN_PHAM_SERVICE.update(dongSP);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(rootPane, check);
            return;
        }
        listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getList());
        resetFormViewDongSP();
        JOptionPane.showMessageDialog(rootPane, "Cập nhật dòng sản phẩm thành công");
    }//GEN-LAST:event_btnViewDongSanPhamUpdateActionPerformed

    private void btnViewDongSanPhamDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDongSanPhamDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa dòng sản phẩm đã chọn ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            String check = DONG_SAN_PHAM_SERVICE.delete(listDongSPs.get(checkViewDongSP));
            if (!check.equals("")) {
                JOptionPane.showMessageDialog(rootPane, check);
                return;
            }
            listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getList());
            resetFormViewDongSP();
            JOptionPane.showMessageDialog(rootPane, "Xóa dòng sản phẩm thành công");
        } else {
            return;
        }
    }//GEN-LAST:event_btnViewDongSanPhamDeleteActionPerformed

    private void txtViewDongSanPhamSreachCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtViewDongSanPhamSreachCaretUpdate
        // TODO add your handling code here:
        jlViewDongSanPhamError.setText("");
        if (!"".equals(txtViewDongSanPhamSreach.getText())) {
            listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getListByTen(txtViewDongSanPhamSreach.getText()));
            if (tblDongSanPham.getRowCount() == 0) {
                jlViewDongSanPhamError.setText("Không có dữ liệu");
            }
        } else {
            listDongSPs = getListDongSP(DONG_SAN_PHAM_SERVICE.getList());
        }
    }//GEN-LAST:event_txtViewDongSanPhamSreachCaretUpdate

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnResetCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCTSPActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetCTSPActionPerformed

    private void btnResetSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSPActionPerformed
        // TODO add your handling code here:
        resetFormViewSanPham();
    }//GEN-LAST:event_btnResetSPActionPerformed

    private void btnResetNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNSXActionPerformed
        // TODO add your handling code here:
        resetFormViewNhaSanxuat();
    }//GEN-LAST:event_btnResetNSXActionPerformed

    private void btnResetMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetMSActionPerformed
        // TODO add your handling code here:
        resetFormViewMauSac();
    }//GEN-LAST:event_btnResetMSActionPerformed

    private void btnResetDSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDSPActionPerformed
        // TODO add your handling code here:
        resetFormViewDongSP();
    }//GEN-LAST:event_btnResetDSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLyThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLyThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLyThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLyThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuanLyThongTinSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlChiTietSP;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnResetCTSP;
    private javax.swing.JButton btnResetDSP;
    private javax.swing.JButton btnResetMS;
    private javax.swing.JButton btnResetNSX;
    private javax.swing.JButton btnResetSP;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDongSanPhamDelete;
    private javax.swing.JButton btnViewDongSanPhamUpdate;
    private javax.swing.JButton btnViewMauSacDelete;
    private javax.swing.JButton btnViewMauSacUpdate;
    private javax.swing.JButton btnViewNSXDelete;
    private javax.swing.JButton btnViewNSXUpdate;
    private javax.swing.JButton btnViewSanPhamDelete;
    private javax.swing.JButton btnViewSanPhamUpdate;
    private javax.swing.JComboBox<String> cbDongSP;
    private javax.swing.JComboBox<String> cbMauSac;
    private javax.swing.JComboBox<String> cbNhaSanXuat;
    private javax.swing.JComboBox<String> cbSanPham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlError;
    private javax.swing.JLabel jlSearchErrors;
    private javax.swing.JLabel jlViewDongSanPhamError;
    private javax.swing.JLabel jlViewMauSacError;
    private javax.swing.JLabel jlViewNSXError;
    private javax.swing.JLabel jlViewSanPhamError;
    private javax.swing.JSpinner jsNamBH;
    private javax.swing.JTable tblDongSanPham;
    private javax.swing.JTable tblMauSac;
    private javax.swing.JTable tblNhSanXuat;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtViewDongSPMaDongSP;
    private javax.swing.JTextField txtViewDongSPTenDongSP;
    private javax.swing.JTextField txtViewDongSanPhamSreach;
    private javax.swing.JTextField txtViewMauSacMaMau;
    private javax.swing.JTextField txtViewMauSacSearch;
    private javax.swing.JTextField txtViewMauSacTenMau;
    private javax.swing.JTextField txtViewNSXMaNSX;
    private javax.swing.JTextField txtViewNSXSreach;
    private javax.swing.JTextField txtViewNSXTenNSX;
    private javax.swing.JTextField txtViewSanPhamSreach;
    // End of variables declaration//GEN-END:variables

    public ChiTietSanPham insertData() {
        jlError.setText("");
        DongSP dongSP = (DongSP) cbDongSP.getSelectedItem();
        MauSac mauSac = (MauSac) cbMauSac.getSelectedItem();
        NhaSanXuat nhaSanXuat = (NhaSanXuat) cbNhaSanXuat.getSelectedItem();
        SanPham sanPham = (SanPham) cbSanPham.getSelectedItem();
        int namBH = Integer.parseInt(jsNamBH.getValue().toString());
        String moTa = txtMoTa.getText().trim();
        String soLuongTon = txtSoLuongTon.getText().trim();
        String giaNhap = txtGiaNhap.getText().trim();
        String giaBan = txtGiaBan.getText().trim();
        if (!Validate.checkEmtry(moTa, soLuongTon, giaBan, giaNhap)) {
            jlError.setText("Lỗi:Không được để trống dữ liệu");
            return null;
        }
        if (dongSP == null || nhaSanXuat == null || mauSac == null || sanPham == null) {
            jlError.setText("Lỗi:Không được để trống sản phẩm,dòng SP,Nhà sản xuất,Màu sắc");
            return null;
        }
        if (!Validate.checkFormatDouble(giaBan, giaNhap)) {
            jlError.setText("Lỗi:Giá bán và Giá nhập phải là số");
            return null;
        }
        if (!Validate.checkFormatInt(soLuongTon)) {
            jlError.setText("Lỗi:Số lượng tồn không hợp lệ");
            return null;
        }
        if (!Validate.checkFormatSmallerThanRezo(Double.parseDouble(giaBan),
                Double.parseDouble(giaNhap), Double.parseDouble(soLuongTon))) {
            jlError.setText("Lỗi:Số lượng tồn,giá nhập,giá bán phải lớn hơn 0");
            return null;
        }
        BigDecimal giaNhapBigDecimal = new BigDecimal(giaNhap);
        BigDecimal giaBanBigDecimal = new BigDecimal(giaBan);
        if (giaNhapBigDecimal.compareTo(giaBanBigDecimal) > 0) {
            jlError.setText("Lỗi:Giá bán không được nhỏ hơn giá nhập");
            return null;
        }
        return ChiTietSanPham.builder().id(id).sanPham(sanPham).dongSP(dongSP).mauSac(mauSac)
                .nhaSanXuat(nhaSanXuat).namBH(namBH).
                soLuongTon(Integer.parseInt(soLuongTon)).moTa(moTa).giaBan(BigDecimal.valueOf(Double.parseDouble(giaBan)))
                .giaNhap(BigDecimal.valueOf(Double.parseDouble(giaNhap))).build();

    }

    private List<ChiTietSanPham> getListChiTietSanPham(List<ChiTietSanPham> list) {
        modelChiTietSanPham.setRowCount(0);
        list.forEach((t) -> {
            modelChiTietSanPham.addRow(t.getObj(modelChiTietSanPham.getRowCount() + 1));
        });
        return list;

    }

    private void getCbb() {
        boxModelDongSP.removeAllElements();
        boxModelMauSac.removeAllElements();
        boxModelNhaSX.removeAllElements();
        boxModelSanPham.removeAllElements();
        boxModelSanPham.addAll(SAN_PHAM_SERVICE.getList());
        boxModelDongSP.addAll(DONG_SAN_PHAM_SERVICE.getList());
        boxModelMauSac.addAll(MAU_SAC_SERVICE.getList());
        boxModelNhaSX.addAll(NHA_SAN_XUAT_SERVICE.getList());
    }

    private void resetForm() {
        txtGiaBan.setText("");
        txtGiaNhap.setText("");
        txtMoTa.setText("");
        txtSearch.setText("");
        txtSoLuongTon.setText("");
        jsNamBH.setValue(0);
        ctspCheck = null;
        check = -1;
        id = "";
        idSanPham = "";
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        cbDongSP.setSelectedIndex(-1);
        cbMauSac.setSelectedIndex(-1);
        cbNhaSanXuat.setSelectedIndex(-1);
        cbSanPham.setSelectedIndex(-1);
    }

    private void fillForm(ChiTietSanPham chiTietSanPham) {
        boxModelDongSP.setSelectedItem(chiTietSanPham.getDongSP());
        boxModelMauSac.setSelectedItem(chiTietSanPham.getMauSac());
        boxModelNhaSX.setSelectedItem(chiTietSanPham.getNhaSanXuat());
        boxModelSanPham.setSelectedItem(chiTietSanPham.getSanPham());
        txtSoLuongTon.setText(chiTietSanPham.getSoLuongTon() + "");
        jsNamBH.setValue(chiTietSanPham.getNamBH());
        txtGiaBan.setText(chiTietSanPham.getGiaBan() + "");
        txtGiaNhap.setText(chiTietSanPham.getGiaNhap() + "");
        txtMoTa.setText(chiTietSanPham.getMoTa());
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }

    private List<SanPham> getListSanPham(List<SanPham> list) {
        modelSanPham.setRowCount(0);
        list.forEach((t) -> {
            modelSanPham.addRow(t.getObj(tblSanPham.getRowCount() + 1));
        });
        return list;
    }

    private List<MauSac> getListMauSac(List<MauSac> list) {
        modelMauSac.setRowCount(0);
        list.forEach((t) -> {
            modelMauSac.addRow(t.getObj(tblMauSac.getRowCount() + 1));
        });
        return list;
    }

    private List<DongSP> getListDongSP(List<DongSP> list) {
        modelDongSanPham.setRowCount(0);
        list.forEach((t) -> {
            modelDongSanPham.addRow(t.getObj(tblDongSanPham.getRowCount() + 1));
        });
        return list;
    }

    private List<NhaSanXuat> getListNhaSanXuat(List<NhaSanXuat> list) {
        modelNhaSanXuat.setRowCount(0);
        list.forEach((t) -> {
            modelNhaSanXuat.addRow(t.getObj(tblNhSanXuat.getRowCount() + 1));
        });
        return list;
    }

    SanPham insertDataViewSanPham() {
        String ma = txtMaSanPham.getText().trim();
        String ten = txtTenSanPham.getText().trim();
        jlViewSanPhamError.setText("");
        if (!Validate.checkEmtry(ma, ten)) {
            jlViewSanPhamError.setText("Không để trống dữ liệu");
            return null;
        }
        return SanPham.builder().id(idSanPham).ma(ma).ten(ten).build();
    }

    MauSac insertDataViewMauSac() {
        String ma = txtViewMauSacMaMau.getText().trim();
        String ten = txtViewMauSacTenMau.getText().trim();
        jlViewMauSacError.setText("");
        if (!Validate.checkEmtry(ma, ten)) {
            jlViewMauSacError.setText("Không để trống dữ liệu");
            return null;
        }
        return MauSac.builder().id(idMauSac).ma(ma).ten(ten).build();
    }

    DongSP insertDataViewDongSP() {
        String ma = txtViewDongSPMaDongSP.getText().trim();
        String ten = txtViewDongSPTenDongSP.getText().trim();
        jlViewDongSanPhamError.setText("");
        if (!Validate.checkEmtry(ma, ten)) {
            jlViewDongSanPhamError.setText("Không để trống dữ liệu");
            return null;
        }
        return DongSP.builder().id(idDongSP).ma(ma).ten(ten).build();
    }

    NhaSanXuat insertDataViewNhaSanXuat() {
        String ma = txtViewNSXMaNSX.getText().trim();
        String ten = txtViewNSXTenNSX.getText().trim();
        jlViewNSXError.setText("");
        if (!Validate.checkEmtry(ma, ten)) {
            jlViewNSXError.setText("Không để trống dữ liệu");
            return null;
        }
        return NhaSanXuat.builder().id(idNSX).ma(ma).ten(ten).build();
    }

    private void resetFormViewSanPham() {
        txtMaSanPham.setText("");
        txtTenSanPham.setText("");
        idSanPham = "";
        checkViewSP = -1;
        btnViewSanPhamDelete.setEnabled(false);
        btnViewSanPhamUpdate.setEnabled(false);
    }

    private void resetFormViewDongSP() {
        txtViewDongSPMaDongSP.setText("");
        txtViewDongSPTenDongSP.setText("");
        idDongSP = "";
        checkViewDongSP = -1;
        btnViewDongSanPhamDelete.setEnabled(false);
        btnViewDongSanPhamUpdate.setEnabled(false);
    }

    private void resetFormViewNhaSanxuat() {
        txtViewNSXMaNSX.setText("");
        txtViewNSXTenNSX.setText("");
        idNSX = "";
        checkViewNSX = -1;
        btnViewNSXDelete.setEnabled(false);
        btnViewNSXUpdate.setEnabled(false);
    }

    private void resetFormViewMauSac() {
        txtViewMauSacMaMau.setText("");
        txtViewMauSacTenMau.setText("");
        idMauSac = "";
        checkViewMauSac = -1;
        btnViewMauSacDelete.setEnabled(false);
        btnViewMauSacUpdate.setEnabled(false);
    }

    private void fillFormSanPham(SanPham sanPham) {
        txtMaSanPham.setText(sanPham.getMa());
        txtTenSanPham.setText(sanPham.getTen());
        idSanPham = sanPham.getId();
        btnViewSanPhamDelete.setEnabled(true);
        btnViewSanPhamUpdate.setEnabled(true);
    }

    private void fillFormDongSP(DongSP dongSP) {
        txtViewDongSPMaDongSP.setText(dongSP.getMa());
        txtViewDongSPTenDongSP.setText(dongSP.getTen());
        idDongSP = dongSP.getId();
        btnViewDongSanPhamDelete.setEnabled(true);
        btnViewDongSanPhamUpdate.setEnabled(true);
    }

    private void fillFormNSX(NhaSanXuat nhaSanXuat) {
        txtViewNSXMaNSX.setText(nhaSanXuat.getMa());
        txtViewNSXTenNSX.setText(nhaSanXuat.getTen());
        idNSX = nhaSanXuat.getId();
        btnViewNSXDelete.setEnabled(true);
        btnViewNSXUpdate.setEnabled(true);
    }

    private void fillFormMauSac(MauSac mauSac) {
        txtViewMauSacMaMau.setText(mauSac.getMa());
        txtViewMauSacTenMau.setText(mauSac.getTen());
        idMauSac = mauSac.getId();
        btnViewMauSacDelete.setEnabled(true);
        btnViewMauSacUpdate.setEnabled(true);
    }
}
